apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: build-deploy-go
spec:
  pipelineRef:
    name: build-and-deploy
  serviceAccountName: skopeo
  params:
  - name: git-url
    value: git@github.com:trevorbox/s2i.git
  - name: git-revision
    value: release/0.1.0
  - name: IMAGE
    value: quay.io/trevorbox/pipeline-test-go
    # value: docker.io/trevorbox/go-app
  - name: CONTEXT
    value: go
  - name: GROUP_EMAIL
    value: myteam@example.com
  - name: builder-image-repository
    value: registry.access.redhat.com/ubi9/go-toolset
  - name: builder-image-tag
    value: latest
  - name: base-image-repository
    value: registry.access.redhat.com/ubi9/ubi-micro
  - name: base-image-tag
    value: latest
  - name: monorepo-git-url
    value: git@github.com:trevorbox/openshift-gitops.git
  - name: monorepo-git-revision
    value: main
  - name: files
    value:
      - "./appofapps/deploy/helm/app/values-build.yaml"
      - "./appofapps/deploy/helm/app/values-dev.yaml"
  - name: application-names
    value:
      - "hr-echo-dev"
      - "hr-echo-build"
  workspaces:
  - name: shared-workspace
    persistentVolumeClaim:
      claimName: source-pvc
  - name: monorepo-workspace
    persistentVolumeClaim:
      claimName: monorepo-pvc
  - name: ssh-creds
    secret:
      secretName: my-ssh-credentials
