apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ .Values.context }}-rootapp
  {{- if .Values.addFinalizer }}
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  {{- end }}
spec:
  destination:
    name: ''
    namespace: {{ .Release.Namespace }}
    server: 'https://kubernetes.default.svc'
  source:
    path: argocd/helm/app
    repoURL: 'https://github.com/trevorbox/openshift-gitops.git'
    targetRevision: {{ .Values.source.targetRevision }}
    helm: 
      valueFiles:
        - values-{{ .Values.clusterName }}.yaml 
  project: default
  syncPolicy:
    automated: 
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
