kind: ImageStream
apiVersion: image.openshift.io/v1
metadata:
  name: ubi9-go-toolset
spec:
  tags:
    - name: latest
      from:
        kind: DockerImage
        name: registry.access.redhat.com/ubi9/go-toolset
      importPolicy:
        scheduled: true