kind: ImageStream
apiVersion: image.openshift.io/v1
metadata:
  name: ubi9-micro
spec:
  tags:
    - name: latest
      from:
        kind: DockerImage
        name: registry.access.redhat.com/ubi9/ubi-micro
      importPolicy:
        scheduled: true