{{- range .Values.apps }}
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ $.Values.context }}-{{ .env }}
  {{- if .addFinalizer }}
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  {{- end }}
spec:
  destination:
    name: ''
    namespace: {{ $.Values.org }}-{{ $.Values.context }}-{{ .env }}
    server: 'https://kubernetes.default.svc'
  source:
    path: {{ (.source).path | default $.Values.defaults.source.path | quote }}
    repoURL: {{ (.source).repoURL | default $.Values.defaults.source.repoURL | quote }}
    targetRevision: {{ (.source).targetRevision | default $.Values.defaults.source.targetRevision | quote }}
    helm:
      valueFiles:
        - values-{{ .env }}.yaml
  project: default
  syncPolicy:
    automated: 
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
...
{{- end }}